//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int id_Cita { get; set; }
        public string estado { get; set; }
        public string fecha_Cita { get; set; }
        public Nullable<int> id_Paciente { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
